### ISSUE TITLE
autocomplete not trigger change method

### ISSUE THREAD

**Issue by blu94** [godbasin/vue-select2#30] opened 2020-03-21 12:45 UTC
When user autocomplete the field, the change method is not trigger, because when the select2 field have selected some value, it will trigger an alert, but the alert is not showing when the field is filled by autocomplete.

And although the select2 field is selected, but the properties is still null.

**Comment by godbasin** [comment] 2020-03-22 02:29
Duplicate of #27

**Closed** 2020-07-07 12:21 UTC
